In [ ]:
print("hello")

hello

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving california_housing_test.csv to california_housing_test (1).csv

In [ ]:
df=pd.read_csv("california_housing_test.csv")

In [ ]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [ ]:
import pandas as pd

In [ ]:
data={
    "Name":["Anu","Rahul","Kiran","Priya","Sanjeev"],
    "Marks": [78,85,92,67,45],
    "Attendance": [85,90,95,72,38],
    "Subject": ["Maths","Physics","Chemistry","English","Hindi"]}
df=pd.DataFrame(data)

In [ ]:
df.head()

      Name  Marks  Attendance    Subject
0      Anu     78          85      Maths
1    Rahul     85          90    Physics
2    Kiran     92          95  Chemistry
3    Priya     67          72    English
4  Sanjeev     45          38      Hindi

In [ ]:
df["Marks"]

0    78
1    85
2    92
3    67
4    45
Name: Marks, dtype: int64

In [ ]:
df[["Name","Marks"]]

      Name  Marks
0      Anu     78
1    Rahul     85
2    Kiran     92
3    Priya     67
4  Sanjeev     45

In [ ]:
df.iloc[0]

Name            Anu
Marks            78
Attendance       85
Subject       Maths
Name: 0, dtype: object

In [ ]:
df.iloc[0:2]

    Name  Marks  Attendance  Subject
0    Anu     78          85    Maths
1  Rahul     85          90  Physics

In [ ]:
df[df["Marks"]>80]

    Name  Marks  Attendance    Subject
1  Rahul     85          90    Physics
2  Kiran     92          95  Chemistry