In [ ]:
print("Welcome to Data Analytics")

Welcome to Data Analytics

In [ ]:
import numpy as np
import pandas as pd

print("Numpy version: ",np.__version__)
print("Pandas version: ",pd.__version__)

Numpy version:  2.1.3
Pandas version:  2.2.3

In [ ]:
marks=np.array([78,85,92,67,88])

print("Marks: ",marks)
print("Type: ",type(marks))

Marks:  [78 85 92 67 88]
Type:  <class 'numpy.ndarray'>

Array properties

In [ ]:
print("Number of dimension: ",marks.ndim)
print("Shape: ",marks.shape)
print("Number of elements: ",marks.size)

Number of dimension:  1
Shape:  (5,)
Number of elements:  5

In [ ]:
marks=np.array([78,85,92,67,88])

print("Original: ",marks)
print("Add 5: ",marks + 5)
print("Multiply by 2: ",marks * 2)
print("Divide by 2: ",marks / 2)
print("Square: ",marks ** 2)

Original:  [78 85 92 67 88]
Add 5:  [83 90 97 72 93]
Multiply by 2:  [156 170 184 134 176]
Divide by 2:  [39.  42.5 46.  33.5 44. ]
Square:  [6084 7225 8464 4489 7744]

In [ ]:
print("Sum: ",marks.sum())
print("Mean: ",marks.mean()) #sum of all data points divided by total data points
print("Maximum: ",marks.max())
print("Minimum: ",marks.min())

Sum:  410
Mean:  82.0
Maximum:  92
Minimum:  67

Numpy Indexing

In [ ]:
print("First mark: ",marks[0])
print("Second mark: ",marks[1])
print("Last mark: ",marks[-1])

First mark:  78
Second mark:  85
Last mark:  88

Numpy Slicing

In [ ]:
print("Index 1 to 3: ",marks[1:4])
print("First three: ",marks[:3])
print("From index 2: ",marks[2:])
print("Every second element: ",marks[::2])

Index 1 to 3:  [85 92 67]
First three:  [78 85 92]
From index 2:  [92 67 88]
Every second element:  [78 92 88]

Two Dimensional Array

In [ ]:
student_marks=np.array([[78,85,92],[67,88,76],[90,95,89]])

print(student_marks)
print("Shape: ",student_marks.shape)

[[78 85 92]
 [67 88 76]
 [90 95 89]]
Shape:  (3, 3)

In [ ]:
print("Mean of all values: ",student_marks.mean())
print("Column-wise mean: ",student_marks.mean(axis=0))
print("Row-wose mean: ",student_marks.mean(axis=1))

Mean of all values:  84.44444444444444
Column-wise mean:  [78.33333333 89.33333333 85.66666667]
Row-wose mean:  [85.         77.         91.33333333]

Data frame

In [ ]:
data={
    "Name":["Anu","Rahul","Kiran","Priya"],
    "Branch":["CSE","AIML","CSE","AIML"],
    "Marks":[85,91,76,88]
}
df=pd.DataFrame(data)
df

    Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML     91
2  Kiran    CSE     76
3  Priya   AIML     88

In [ ]:
print("Shape: ",df.shape)
print("\nColumns: ",df.columns)

Shape:  (4, 3)

Columns:  Index(['Name', 'Branch', 'Marks'], dtype='object')

In [ ]:
df.head()

    Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML     91
2  Kiran    CSE     76
3  Priya   AIML     88

In [ ]:
df.tail()

    Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML     91
2  Kiran    CSE     76
3  Priya   AIML     88

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Branch  4 non-null      object
 2   Marks   4 non-null      int64
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

In [ ]:
df.describe()

           Marks
count   4.000000
mean   85.000000
std     6.480741
min    76.000000
25%    82.750000
50%    86.500000
75%    88.750000
max    91.000000

In [ ]:
print("Marks columns: ",df["Marks"])
print("Branch and Marks: ",df[["Branch","Marks"]])

Marks columns:  0    85
1    91
2    76
3    88
Name: Marks, dtype: int64
Branch and Marks:    Branch  Marks
0    CSE     85
1   AIML     91
2    CSE     76
3   AIML     88

In [ ]:
print("First row: \n",df.iloc[0])
print("\nSecond row: \n",df.iloc[1])
print("\nFirst three rows: \n",df.iloc[0:3])

First row:
 Name      Anu
Branch    CSE
Marks      85
Name: 0, dtype: object

Second row:
 Name      Rahul
Branch     AIML
Marks        91
Name: 1, dtype: object

First three rows:
     Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML     91
2  Kiran    CSE     76

In [ ]:
data={
    "Name":["Anu","Rahul","Kiran","Priya","Raavee"],
    "Branch":["CSE","ISE","AIML","CSE","AIML"],
    "Marks":[85,91,76,88,92],
    "Attendence": [92,65,93,45,75]
}
df=pd.DataFrame(data)
df

     Name Branch  Marks  Attendence
0     Anu    CSE     85          92
1   Rahul    ISE     91          65
2   Kiran   AIML     76          93
3   Priya    CSE     88          45
4  Raavee   AIML     92          75

In [ ]:
df[["Name","Marks"]]

     Name  Marks
0     Anu     85
1   Rahul     91
2   Kiran     76
3   Priya     88
4  Raavee     62

In [ ]:
df[df['Marks'] > 80]

    Name Branch  Marks  Attendence
0    Anu    CSE     85          82
1  Rahul    ISE     91          65
3  Priya    CSE     88          45

In [ ]:
df[df["Attendence"]>85]

    Name Branch  Marks  Attendence
2  Kiran   AIML     76          93

In [ ]:
df.head(3)

    Name Branch  Marks  Attendence
0    Anu    CSE     85          82
1  Rahul    ISE     91          65
2  Kiran   AIML     76          93

In [ ]:
df["Marks"].mean()

np.float64(80.4)

In [ ]:
df["Marks"].max()

91

In [ ]:
df[df['Branch']=='CSE']

    Name Branch  Marks  Attendence
0    Anu    CSE     85          82
3  Priya    CSE     88          45

In [ ]:
df[(df['Marks']>=80) & (df['Attendence']>85)]

  Name Branch  Marks  Attendence
0  Anu    CSE     85          92