In [ ]:
import pandas as pd
data={
    "Student_ID": [101,102,103,104,105,106,107,108,109,110,110],
    "Name": ["Anu","Bharat","Chetan","Divya","Esha","Farhan","Gaowri","Harish","Isha","Kiran","Kiran"],
    "Department": ["CSE","AIML","CSE","ISE","AIML","CSE","ISE","CSE","AIML","ISE","ISE"],
    "Gender":["F","M","M","F","F","M","F","M","F","M","M"],
    "Attendance":[92,85,78,95,88,None,91,73,86,80,80],
    "Python_Marks":[88,76,91,95,84,72,None,65,89,78,78],
    "Data_Structures_Marks":[82,79,94,90,87,68,92,None,85,74,74],
    "Final_Score":[85,77,93,92,86,70,91,67,87,76,76]
}

df=pd.DataFrame(data)
df

,Student_ID,Name,Department,Gender,Attendance,Python_Marks,Data_Structures_Marks,Final_Score
0,101,Anu,CSE,F,92.0,88.0,82.0,85
1,102,Bharat,AIML,M,85.0,76.0,79.0,77
2,103,Chetan,CSE,M,78.0,91.0,94.0,93
3,104,Divya,ISE,F,95.0,95.0,90.0,92
4,105,Esha,AIML,F,88.0,84.0,87.0,86
5,106,Farhan,CSE,M,NaN,72.0,68.0,70
6,107,Gaowri,ISE,F,91.0,NaN,92.0,91
7,108,Harish,CSE,M,73.0,65.0,NaN,67
8,109,Isha,AIML,F,86.0,89.0,85.0,87
9,110,Kiran,ISE,M,80.0,78.0,74.0,76
10,110,Kiran,ISE,M,80.0,78.0,74.0,76

In [ ]:
df.head()

,Student_ID,Name,Department,Gender,Attendance,Python_Marks,Data_Structures_Marks,Final_Score
0,101,Anu,CSE,F,92.0,88.0,82.0,85
1,102,Bharat,AIML,M,85.0,76.0,79.0,77
2,103,Chetan,CSE,M,78.0,91.0,94.0,93
3,104,Divya,ISE,F,95.0,95.0,90.0,92
4,105,Esha,AIML,F,88.0,84.0,87.0,86

In [ ]:
df.head(3)

,Student_ID,Name,Department,Gender,Attendance,Python_Marks,Data_Structures_Marks,Final_Score
0,101,Anu,CSE,F,92.0,88.0,82.0,85
1,102,Bharat,AIML,M,85.0,76.0,79.0,77
2,103,Chetan,CSE,M,78.0,91.0,94.0,93

In [ ]:
df.tail()

,Student_ID,Name,Department,Gender,Attendance,Python_Marks,Data_Structures_Marks,Final_Score
6,107,Gaowri,ISE,F,91.0,NaN,92.0,91
7,108,Harish,CSE,M,73.0,65.0,NaN,67
8,109,Isha,AIML,F,86.0,89.0,85.0,87
9,110,Kiran,ISE,M,80.0,78.0,74.0,76
10,110,Kiran,ISE,M,80.0,78.0,74.0,76

In [ ]:
df.tail(3)

,Student_ID,Name,Department,Gender,Attendance,Python_Marks,Data_Structures_Marks,Final_Score
8,109,Isha,AIML,F,86.0,89.0,85.0,87
9,110,Kiran,ISE,M,80.0,78.0,74.0,76
10,110,Kiran,ISE,M,80.0,78.0,74.0,76

In [ ]:
rows, columns=df.shape
print("Number of rows:",rows)
print("Number of columns:",columns)

Number of rows: 11
Number of columns: 8

In [ ]:
print(df.columns.tolist())

['Student_ID', 'Name', 'Department', 'Gender', 'Attendance', 'Python_Marks', 'Data_Structures_Marks', 'Final_Score']

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             11 non-null     int64
 1   Name                   11 non-null     object
 2   Department             11 non-null     object
 3   Gender                 11 non-null     object
 4   Attendance             10 non-null     float64
 5   Python_Marks           10 non-null     float64
 6   Data_Structures_Marks  10 non-null     float64
 7   Final_Score            11 non-null     int64
dtypes: float64(3), int64(2), object(3)
memory usage: 836.0+ bytes

In [ ]:
print(df["Python_Marks"].mean())

81.6

In [ ]:
print(df["Python_Marks"].median())

81.0

In [ ]:
print(df["Python_Marks"].mode())

0    78.0
Name: Python_Marks, dtype: float64

In [ ]:
print(df["Gender"].mode())

0    M
Name: Gender, dtype: object

In [ ]:
df.describe()

,Student_ID,Attendance,Python_Marks,Data_Structures_Marks,Final_Score
count,11.000000,10.000000,10.000000,10.000000,11.000000
mean,105.909091,84.800000,81.600000,82.500000,81.818182
std,3.176619,6.972964,9.395034,8.644202,9.042325
min,101.000000,73.000000,65.000000,68.000000,67.000000
25%,103.500000,80.000000,76.500000,75.250000,76.000000
50%,106.000000,85.500000,81.000000,83.500000,85.000000
75%,108.500000,90.250000,88.750000,89.250000,89.000000
max,110.000000,95.000000,95.000000,94.000000,93.000000

In [ ]:
print("Mean: ",df["Python_Marks"].mean())
print("Median: ",df["Python_Marks"].median())

Mean:  81.6
Median:  81.0

In [ ]:
df.isnull()

,Student_ID,Name,Department,Gender,Attendance,Python_Marks,Data_Structures_Marks,Final_Score
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
5,False,False,False,False,True,False,False,False
6,False,False,False,False,False,True,False,False
7,False,False,False,False,False,False,True,False
8,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False

In [ ]:
print(df.isnull().sum())

Student_ID               0
Name                     0
Department               0
Gender                   0
Attendance               1
Python_Marks             1
Data_Structures_Marks    1
Final_Score              0
dtype: int64

In [ ]:
missing_percentage=(df.isnull().sum()/len(df))*100
print(missing_percentage)

Student_ID               0.000000
Name                     0.000000
Department               0.000000
Gender                   0.000000
Attendance               9.090909
Python_Marks             9.090909
Data_Structures_Marks    9.090909
Final_Score              0.000000
dtype: float64

In [ ]:
duplicated_rows=df.duplicated()
print(duplicated_rows)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
dtype: bool

In [ ]:
df.duplicated().sum()

np.int64(1)

In [ ]:
df[df.duplicated()]

,Student_ID,Name,Department,Gender,Attendance,Python_Marks,Data_Structures_Marks,Final_Score
10,110,Kiran,ISE,M,80.0,78.0,74.0,76

In [ ]:
import pandas as pd

data = {
    "Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 110],
    "Name": ["Aarav", "Priya", "Rahul", "Ananya", "Vikram", "Neha", "Rohan", "Sneha", "Karan", "Meera", "Meera"],
    "Department": ["CSE", "HR", "Finance", "Marketing", "CSE", "Finance", "HR", "CSE", "AIML", "Marketing", "Marketing"],
    "Gender": ["M", "F", "M", "F", "M", "F", "M", "F", "M", "F", "F"],
    "Experience": [2, 5, 8, 3, 10, None, 4, 6, 2, 7, 7],
    "Salary": [45000, 52000, 65000, 48000, 75000, 68000, 50000, None, 55000, 62000, 62000]
}

df = pd.DataFrame(data)
df

    Employee_ID    Name Department Gender  Experience   Salary
0           101   Aarav        CSE      M         2.0  45000.0
1           102   Priya         HR      F         5.0  52000.0
2           103   Rahul    Finance      M         8.0  65000.0
3           104  Ananya  Marketing      F         3.0  48000.0
4           105  Vikram        CSE      M        10.0  75000.0
5           106    Neha    Finance      F         NaN  68000.0
6           107   Rohan         HR      M         4.0  50000.0
7           108   Sneha        CSE      F         6.0      NaN
8           109   Karan       AIML      M         2.0  55000.0
9           110   Meera  Marketing      F         7.0  62000.0
10          110   Meera  Marketing      F         7.0  62000.0

In [ ]:
df.head()

   Employee_ID    Name Department Gender  Experience   Salary
0          101   Aarav        CSE      M         2.0  45000.0
1          102   Priya         HR      F         5.0  52000.0
2          103   Rahul    Finance      M         8.0  65000.0
3          104  Ananya  Marketing      F         3.0  48000.0
4          105  Vikram        CSE      M        10.0  75000.0

In [ ]:
df.shape

(11, 6)

In [ ]:
df.dtypes

Employee_ID      int64
Name            object
Department      object
Gender          object
Experience     float64
Salary         float64
dtype: object

In [ ]:
df["Salary"].mean()

np.float64(58200.0)

In [ ]:
df["Salary"].median()

58500.0

In [ ]:
print("Minimum Experience:", df["Experience"].min())
print("Maximum Experience:", df["Experience"].max())

Minimum Experience: 2.0
Maximum Experience: 10.0

In [ ]:
df.describe()

       Employee_ID  Experience        Salary
count    11.000000   10.000000     10.000000
mean    105.909091    5.400000  58200.000000
std       3.176619    2.674987   9704.523573
min     101.000000    2.000000  45000.000000
25%     103.500000    3.250000  50500.000000
50%     106.000000    5.500000  58500.000000
75%     108.500000    7.000000  64250.000000
max     110.000000   10.000000  75000.000000

In [ ]:
df.isnull().sum()

Employee_ID    0
Name           0
Department     0
Gender         0
Experience     1
Salary         1
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(1)

In [ ]:
df[df.duplicated()]

    Employee_ID   Name Department Gender  Experience   Salary
10          110  Meera  Marketing      F         7.0  62000.0